export enum Events {
    UPDATE,
    DESTROY,
    PIPE_DESTROYED,
    CLOSEST_PIPE_MOVED,
    PIPE_BEYOND_BIRD,
    BIRD_DIED,
    GENETICALLY_TRAINED_BIRD_DIED,
    PLAYER_CONTROLLED_BIRD_FLAPPED,
}
